FROM python:3.10-buster
WORKDIR /app

# setup poetry
RUN pip install poetry
ADD poetry.lock /app
ADD pyproject.toml /app
RUN poetry install
RUN poetry export --dev -f requirements.txt --output requirements.txt
RUN pip install -r requirements.txt

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH /app/server

RUN apt update \
    && apt install -y libpq5 libxml2 curl make \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# setup node
RUN \
    curl -sL https://deb.nodesource.com/setup_16.x | bash -\
    && apt install -y nodejs
