FROM node:16.15.0-buster
WORKDIR /app/ui

# install app
RUN apt update \
    && apt install -y git default-jre

ADD ui/package.json /app/ui
ADD ui/package-lock.json /app/ui

RUN npm install && mv ./node_modules / && chown -R node /node_modules
ENV PATH $PATH:/node_modules/.bin

USER node
