version: '3'
services:
  # web:
  #   build: .
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8000:80"
  db:
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: denkidb
      POSTGRES_USER: user
      POSTGRES_DB: denkidb
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
