version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile-local
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      db_user: user
      db_pass: denkidb
      db_host: db
      db_name: denkidb
    working_dir: /app/server
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
  db:
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: denkidb
      POSTGRES_USER: user
      POSTGRES_DB: denkidb
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
