"""create forecasts

Revision ID: 4f6208794336
Revises: 
Create Date: 2022-02-21 00:59:58.314388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6208794336'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area', sa.Enum('hokkaido', 'tohoku', 'tokyo', 'chubu', 'hokuriku', 'kansai', 'chugoku', 'shikoku', 'kyushu', 'okinawa', name='area'), nullable=False),
    sa.Column('forecast_type', sa.Enum('demand', 'usage', name='forecasttype'), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('peak_hour_24', sa.Integer(), nullable=False),
    sa.Column('max_demand_kw', sa.Float(), nullable=False),
    sa.Column('supply_kw', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area', 'forecast_type', 'target_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecast')
    # ### end Alembic commands ###
