/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Area,
    AreaFromJSON,
    AreaFromJSONTyped,
    AreaToJSON,
} from './Area';

/**
 * 
 * @export
 * @interface DemandForecast
 */
export interface DemandForecast {
    /**
     * 
     * @type {Area}
     * @memberof DemandForecast
     */
    area: Area;
    /**
     * 
     * @type {Date}
     * @memberof DemandForecast
     */
    dt: Date;
    /**
     * 
     * @type {number}
     * @memberof DemandForecast
     */
    actualResult: number;
    /**
     * 
     * @type {number}
     * @memberof DemandForecast
     */
    forecastDemand: number;
    /**
     * 
     * @type {number}
     * @memberof DemandForecast
     */
    forecastSupply: number;
}

export function DemandForecastFromJSON(json: any): DemandForecast {
    return DemandForecastFromJSONTyped(json, false);
}

export function DemandForecastFromJSONTyped(json: any, ignoreDiscriminator: boolean): DemandForecast {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'area': AreaFromJSON(json['area']),
        'dt': (new Date(json['dt'])),
        'actualResult': json['actual_result'],
        'forecastDemand': json['forecast_demand'],
        'forecastSupply': json['forecast_supply'],
    };
}

export function DemandForecastToJSON(value?: DemandForecast | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'area': AreaToJSON(value.area),
        'dt': (value.dt.toISOString()),
        'actual_result': value.actualResult,
        'forecast_demand': value.forecastDemand,
        'forecast_supply': value.forecastSupply,
    };
}

