/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DemandPeakForecast,
    DemandPeakForecastFromJSON,
    DemandPeakForecastFromJSONTyped,
    DemandPeakForecastToJSON,
} from './DemandPeakForecast';
import {
    UsagePeakForecast,
    UsagePeakForecastFromJSON,
    UsagePeakForecastFromJSONTyped,
    UsagePeakForecastToJSON,
} from './UsagePeakForecast';

/**
 * 
 * @export
 * @interface ForecastListResponse
 */
export interface ForecastListResponse {
    /**
     * 
     * @type {Array<DemandPeakForecast>}
     * @memberof ForecastListResponse
     */
    demand: Array<DemandPeakForecast>;
    /**
     * 
     * @type {Array<UsagePeakForecast>}
     * @memberof ForecastListResponse
     */
    usage: Array<UsagePeakForecast>;
}

export function ForecastListResponseFromJSON(json: any): ForecastListResponse {
    return ForecastListResponseFromJSONTyped(json, false);
}

export function ForecastListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForecastListResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'demand': ((json['demand'] as Array<any>).map(DemandPeakForecastFromJSON)),
        'usage': ((json['usage'] as Array<any>).map(UsagePeakForecastFromJSON)),
    };
}

export function ForecastListResponseToJSON(value?: ForecastListResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'demand': ((value.demand as Array<any>).map(DemandPeakForecastToJSON)),
        'usage': ((value.usage as Array<any>).map(UsagePeakForecastToJSON)),
    };
}

