/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AreaDemandForecast,
    AreaDemandForecastFromJSON,
    AreaDemandForecastFromJSONTyped,
    AreaDemandForecastToJSON,
} from './AreaDemandForecast';

/**
 * 
 * @export
 * @interface ForecastListResponse
 */
export interface ForecastListResponse {
    /**
     * 
     * @type {Array<AreaDemandForecast>}
     * @memberof ForecastListResponse
     */
    data: Array<AreaDemandForecast>;
}

export function ForecastListResponseFromJSON(json: any): ForecastListResponse {
    return ForecastListResponseFromJSONTyped(json, false);
}

export function ForecastListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForecastListResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(AreaDemandForecastFromJSON)),
    };
}

export function ForecastListResponseToJSON(value?: ForecastListResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(AreaDemandForecastToJSON)),
    };
}

