/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Area,
    AreaFromJSON,
    AreaFromJSONTyped,
    AreaToJSON,
} from './Area';

/**
 * 使用率ピーク時
 * @export
 * @interface UsagePeakForecast
 */
export interface UsagePeakForecast {
    /**
     * 
     * @type {Area}
     * @memberof UsagePeakForecast
     */
    area: Area;
    /**
     * 
     * @type {number}
     * @memberof UsagePeakForecast
     */
    hour24: number;
    /**
     * 
     * @type {number}
     * @memberof UsagePeakForecast
     */
    maxDemandKw: number;
    /**
     * 
     * @type {number}
     * @memberof UsagePeakForecast
     */
    supplyKw: number;
}

export function UsagePeakForecastFromJSON(json: any): UsagePeakForecast {
    return UsagePeakForecastFromJSONTyped(json, false);
}

export function UsagePeakForecastFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsagePeakForecast {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'area': AreaFromJSON(json['area']),
        'hour24': json['hour_24'],
        'maxDemandKw': json['max_demand_kw'],
        'supplyKw': json['supply_kw'],
    };
}

export function UsagePeakForecastToJSON(value?: UsagePeakForecast | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'area': AreaToJSON(value.area),
        'hour_24': value.hour24,
        'max_demand_kw': value.maxDemandKw,
        'supply_kw': value.supplyKw,
    };
}

