/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ForecastListResponse,
    ForecastListResponseFromJSON,
    ForecastListResponseToJSON,
} from '../models';

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Forecast List
     */
    async forecastListApiForecastGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<ForecastListResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/forecast`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ForecastListResponseFromJSON(jsonValue));
    }

    /**
     * Forecast List
     */
    async forecastListApiForecastGet(initOverrides?: RequestInit): Promise<ForecastListResponse> {
        const response = await this.forecastListApiForecastGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Root
     */
    async rootPingGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/ping`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Root
     */
    async rootPingGet(initOverrides?: RequestInit): Promise<any> {
        const response = await this.rootPingGetRaw(initOverrides);
        return await response.value();
    }

}
